import{createClient}from'@/lib/supabase/server';import type{Agent,Region,Driver,Order,OrderStatus,PaymentStatus}from'@/lib/types/database';
export interface AgentWithRegion extends Omit<Agent,'user'|'region'>{user:{id:string;full_name:string;email:string;phone:string;avatar_url:string};region:Region}
export async function getAgentByUserId(userId:string):Promise<AgentWithRegion|null>{const db=await createClient();const{data,error}=await db.from('agents').select('*, user:users!agents_user_id_fkey(id,full_name,email,phone,avatar_url), region:regions(*)').eq('user_id',userId).eq('is_active',true).single();return error||!data?null:data as unknown as AgentWithRegion}
export async function getAgentRegionStats(regionId:string){const db=await createClient();const{data:drivers}=await db.from('drivers').select('id,status,is_blocked').eq('region_id',regionId);const{data:orders}=await db.from('orders').select('id,status').eq('region_id',regionId);return{totalDrivers:drivers?.length||0,onlineDrivers:(drivers||[]).filter((d:any)=>d.status==='online').length,blockedDrivers:(drivers||[]).filter((d:any)=>d.is_blocked).length,totalOrders:orders?.length||0,activeOrders:(orders||[]).filter((o:any)=>['accepted','in_progress'].includes(o.status)).length,deliveredOrders:(orders||[]).filter((o:any)=>o.status==='delivered').length,pendingPaymentsCount:0,totalPendingPaymentsAmount:0}}
export async function getAgentDrivers(regionId:string,statusFilter?:string){const db=await createClient();let q=db.from('drivers').select('*, user:users!drivers_user_id_fkey(id,full_name,email,phone,avatar_url,is_active)').eq('region_id',regionId).order('created_at',{ascending:false});if(statusFilter==='online')q=q.eq('status','online');if(statusFilter==='blocked')q=q.eq('is_blocked',true);const{data,error}=await q;return error||!data?[]:data as any[]}
export async function getAgentOrders(agentId:string,statusFilter?:OrderStatus){const db=await createClient();const{data:drivers}=await db.from('drivers').select('id').eq('agent_id',agentId);const ids=(drivers||[]).map((d:any)=>d.id);if(!ids.length)return[];let q=db.from('orders').select('*,order_items(*),customer:users!orders_customer_id_fkey(full_name,phone),driver:drivers(id,user:users(full_name,phone))').in('driver_id',ids).order('created_at',{ascending:false});if(statusFilter)q=q.eq('status',statusFilter);const{data,error}=await q;return error||!data?[]:data as any[]}
export async function getAgentDriverOrderStats(driverIds:string[]){if(!driverIds.length)return{month:0,total:0};const db=await createClient();const{data}=await db.from('orders').select('id,created_at').in('driver_id',driverIds).eq('status','delivered');const start=new Date();start.setDate(1);start.setHours(0,0,0,0);const rows=data||[];return{month:rows.filter((o:any)=>new Date(o.created_at)>=start).length,total:rows.length}}
export async function getAgentPayouts(agentId:string,statusFilter?:PaymentStatus){const db=await createClient();let q=(db as any).from('agent_payout_requests').select('*').eq('agent_id',agentId).order('created_at',{ascending:false});if(statusFilter)q=q.eq('status',statusFilter);const{data,error}=await q;return error||!data?[]:data}
export async function getAgentPayoutSummary(agentId:string){const p=await getAgentPayouts(agentId);return{pendingAmount:p.filter((x:any)=>x.status==='pending').reduce((s:number,x:any)=>s+Number(x.amount),0),paidAmount:p.filter((x:any)=>x.status==='confirmed').reduce((s:number,x:any)=>s+Number(x.amount),0),pendingCount:p.filter((x:any)=>x.status==='pending').length}}
