import { getCurrentUser } from '@/lib/services/auth';
import { getAgentByUserId, getAgentPayouts } from '@/lib/services/agent';
import { redirect } from 'next/navigation';
import Link from 'next/link';
import { AppShell, PageHeader } from '@/components';
import { AgentPaymentsClient } from '@/components/agent/AgentPaymentsClient';
import type { PaymentStatus } from '@/lib/types/database';
export const dynamic='force-dynamic';
interface Props{searchParams:Promise<{status?:string}>}
export default async function AgentPaymentsPage({searchParams}:Props){const user=await getCurrentUser();if(!user||user.role!=='agent')redirect('/login');const agent=await getAgentByUserId(user.id);if(!agent)redirect('/login');const params=await searchParams;const status=params.status as PaymentStatus|undefined;const payments=await getAgentPayouts(agent.id,status);const navItems=[{href:'/agent',label:'الرئيسية',labelEn:'Overview',icon:<span>▦</span>},{href:'/agent/orders',label:'الطلبات',labelEn:'Orders',icon:<span>▣</span>},{href:'/agent/drivers',label:'الطيارين',labelEn:'Drivers',icon:<span>◉</span>},{href:'/agent/payments',label:'مستحقاتي',labelEn:'Payouts',icon:<span>ج</span>},{href:'/agent/profile',label:'المنطقة',labelEn:'Region',icon:<span>⌂</span>}];return <AppShell header={<PageHeader title="مستحقاتي" titleEn="Agent Payouts" subtitle={`منطقة ${agent.region.name_ar||agent.region.name}`} backHref="/agent"/>} navItems={navItems}><div className="max-w-md mx-auto py-2 space-y-3"><div className="flex gap-2 overflow-x-auto pb-2 scrollbar-none"><Link href="/agent/payments" className={`btn btn-sm ${!status?'btn-primary':'btn-outline'}`}>الكل</Link><Link href="/agent/payments?status=pending" className={`btn btn-sm ${status==='pending'?'btn-primary':'btn-outline'}`}>قيد الصرف</Link><Link href="/agent/payments?status=confirmed" className={`btn btn-sm ${status==='confirmed'?'btn-primary':'btn-outline'}`}>تم الصرف</Link><Link href="/agent/payments?status=rejected" className={`btn btn-sm ${status==='rejected'?'btn-primary':'btn-outline'}`}>مرفوض</Link></div><AgentPaymentsClient payments={payments}/></div></AppShell>}
