'use client';
import { useState, useEffect, useCallback, createContext, useContext, type ReactNode } from 'react';
type ToastType='success'|'error'|'warning'|'info';
interface Toast{id:string;type:ToastType;title:string;message?:string;duration?:number}
interface ToastContextValue{toasts:Toast[];toast:(opts:Omit<Toast,'id'>)=>void;dismiss:(id:string)=>void}
const ToastContext=createContext<ToastContextValue|null>(null);
export function ToastProvider({children}:{children:ReactNode}){const[toasts,setToasts]=useState<Toast[]>([]);const dismiss=useCallback((id:string)=>setToasts(p=>p.filter(t=>t.id!==id)),[]);const toast=useCallback((opts:Omit<Toast,'id'>)=>{const id=Math.random().toString(36).slice(2);const next={id,duration:4000,...opts};setToasts(p=>[...p.slice(-4),next]);if(next.duration)window.setTimeout(()=>dismiss(id),next.duration)},[dismiss]);return <ToastContext.Provider value={{toasts,toast,dismiss}}>{children}<ToastContainer toasts={toasts} onDismiss={dismiss}/></ToastContext.Provider>}
export function useToast(){const ctx=useContext(ToastContext);if(!ctx)throw new Error('useToast must be used inside ToastProvider');return ctx}
const ICONS:Record<ToastType,string>={success:'✓',error:'✕',warning:'⚠',info:'ℹ'};
function ToastContainer({toasts,onDismiss}:{toasts:Toast[];onDismiss:(id:string)=>void}){if(!toasts.length)return null;return <div className="toast-container" role="region" aria-label="إشعارات" aria-live="polite">{toasts.map(t=><ToastItem key={t.id} toast={t} onDismiss={onDismiss}/>)}</div>}
function ToastItem({toast,onDismiss}:{toast:Toast;onDismiss:(id:string)=>void}){const[visible,setVisible]=useState(false);useEffect(()=>{const raf=requestAnimationFrame(()=>setVisible(true));return()=>cancelAnimationFrame(raf)},[]);return <div className={['toast',`toast-${toast.type}`,visible?'toast-visible':''].join(' ')} role="alert"><div className={`toast-icon toast-icon-${toast.type}`} aria-hidden>{ICONS[toast.type]}</div><div className="toast-content"><p className="toast-title">{toast.title}</p>{toast.message&&<p className="toast-message">{toast.message}</p>}</div><button type="button" className="toast-close" onClick={()=>onDismiss(toast.id)} aria-label="إغلاق الإشعار">✕</button></div>}
interface AlertProps{type?:ToastType;title?:string;children:ReactNode;onClose?:()=>void}
export function Alert({type='info',title,children,onClose}:AlertProps){const[visible,setVisible]=useState(true);useEffect(()=>{const t=window.setTimeout(()=>setVisible(false),4500);return()=>window.clearTimeout(t)},[]);if(!visible)return null;return <div className={`fixed z-[2100] bottom-[84px] md:bottom-5 right-4 left-4 sm:left-auto sm:min-w-[320px] sm:max-w-[420px] toast toast-popup toast-${type}`} role="alert"><div className={`toast-icon toast-icon-${type}`} aria-hidden>{ICONS[type]}</div><div className="toast-content"><p className="toast-title">{title||(type==='success'?'تم بنجاح':type==='error'?'حدث خطأ':type==='warning'?'تنبيه':'معلومة')}</p><div className="toast-message">{children}</div></div><button type="button" className="toast-close" onClick={()=>{setVisible(false);onClose?.()}} aria-label="إغلاق الإشعار">✕</button></div>}
