'use server';

import { revalidatePath } from 'next/cache';
import { getCurrentUser } from '@/lib/services/auth';
import { createClient, createAdminClient } from '@/lib/supabase/server';
import { reviewPayment } from '@/lib/services/payments';

async function ensureAdmin() { const user=await getCurrentUser(); if(!user||user.role!=='admin') throw new Error('غير مصرح — صلاحيات إدارة مطلوبة'); return user; }
export async function createAgentAccountAction(formData:FormData){await ensureAdmin();const email=String(formData.get('email')||'').trim().toLowerCase();const password=String(formData.get('password')||'');const fullName=String(formData.get('full_name')||'').trim();const phone=String(formData.get('phone')||'').trim();const regionId=String(formData.get('region_id')||'').trim();if(!email||!password||!fullName||!regionId)return{error:'يرجى إدخال الاسم والبريد وكلمة المرور والمنطقة'};if(password.length<6)return{error:'كلمة المرور يجب أن تكون 6 أحرف على الأقل'};const adminSupabase=await createAdminClient();const{data:existingUser}=await adminSupabase.from('users').select('id, role').eq('email',email).maybeSingle();if(existingUser)return{error:'هذا البريد الإلكتروني مستخدم بالفعل'};const{data:authData,error:authError}=await adminSupabase.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{full_name:fullName,phone,role:'agent'}});if(authError||!authData.user)return{error:authError?.message||'فشل إنشاء حساب الوكيل'};const userId=authData.user.id;const{error:userError}=await adminSupabase.from('users').insert({id:userId,email,full_name:fullName,phone,role:'agent',is_active:true,avatar_url:''} as never);if(userError){await adminSupabase.auth.admin.deleteUser(userId);return{error:'فشل إنشاء ملف الوكيل: '+userError.message}}const{error:agentError}=await adminSupabase.from('agents').insert({user_id:userId,region_id:regionId,is_active:true} as never);if(agentError){await adminSupabase.from('users').delete().eq('id',userId);await adminSupabase.auth.admin.deleteUser(userId);return{error:'فشل ربط الوكيل بالمنطقة: '+agentError.message}}revalidatePath('/admin/regions');revalidatePath('/engzadmin/regions');revalidatePath('/admin');revalidatePath('/engzadmin');return{success:true}}
export async function updatePricingSettingsAction(formData:FormData){await ensureAdmin();const supabase=await createClient();const baseDeliveryFee=parseFloat(String(formData.get('base_delivery_fee')));const defaultSearchRadius=parseFloat(String(formData.get('default_search_radius_km')));const radiusExpansionStep=parseFloat(String(formData.get('radius_expansion_step_km')));const maxSearchRadius=parseFloat(String(formData.get('max_search_radius_km')));const blockThreshold=parseFloat(String(formData.get('commission_block_threshold')));const{error}=await supabase.from('pricing_settings').update({base_delivery_fee:baseDeliveryFee,default_search_radius_km:defaultSearchRadius,radius_expansion_step_km:radiusExpansionStep,max_search_radius_km:maxSearchRadius,commission_block_threshold:blockThreshold,updated_at:new Date().toISOString()} as never).eq('is_active',true);if(error)return{error:'فشل حفظ إعدادات التسعير'};revalidatePath('/admin/pricing');return{success:true}}
export async function addDistanceTierAction(formData:FormData){await ensureAdmin();const supabase=await createClient();const{error}=await supabase.from('pricing_distance_tiers').insert({min_distance_km:parseFloat(String(formData.get('min_distance_km'))),max_distance_km:parseFloat(String(formData.get('max_distance_km'))),additional_fee:parseFloat(String(formData.get('additional_fee'))),sort_order:parseInt(String(formData.get('sort_order')),10)||1,is_active:true} as never);if(error)return{error:'فشل إضافة شريحة المسافة'};revalidatePath('/admin/pricing');return{success:true}}
export async function deleteDistanceTierAction(tierId:string){await ensureAdmin();const supabase=await createClient();const{error}=await supabase.from('pricing_distance_tiers').delete().eq('id',tierId);if(error)return{error:'فشل حذف الشريحة'};revalidatePath('/admin/pricing');return{success:true}}
export async function addCommissionTierAction(formData:FormData){await ensureAdmin();const supabase=await createClient();const max=String(formData.get('max_orders')||'');const{error}=await supabase.from('commission_tiers').insert({min_orders:parseInt(String(formData.get('min_orders')),10),max_orders:max?parseInt(max,10):null,commission_type:String(formData.get('commission_type')) as 'fixed'|'percentage',commission_value:parseFloat(String(formData.get('commission_value'))),sort_order:parseInt(String(formData.get('sort_order')),10)||1,is_active:true} as never);if(error)return{error:'فشل إضافة شريحة العمولة'};revalidatePath('/admin/commissions');return{success:true}}
export async function deleteCommissionTierAction(tierId:string){await ensureAdmin();const supabase=await createClient();const{error}=await supabase.from('commission_tiers').delete().eq('id',tierId);if(error)return{error:'فشل حذف الشريحة'};revalidatePath('/admin/commissions');return{success:true}}
export async function createRegionAction(formData:FormData){await ensureAdmin();const supabase=await createClient();const{error}=await supabase.from('regions').insert({name:String(formData.get('name')),name_ar:String(formData.get('name_ar')),whatsapp:String(formData.get('whatsapp')||''),instagram:String(formData.get('instagram')||''),is_active:true} as never);if(error)return{error:'فشل إنشاء المنطقة'};revalidatePath('/admin/regions');return{success:true}}
export async function toggleDriverBlockAction(driverId:string,isBlocked:boolean){await ensureAdmin();const supabase=await createClient();const{error}=await supabase.from('drivers').update({is_blocked:isBlocked} as never).eq('id',driverId);if(error)return{error:'فشل تغيير حالة الحظر'};revalidatePath('/admin/drivers');return{success:true}}
export async function adminReviewPaymentAction(paymentId:string,action:'confirmed'|'rejected',notes?:string){const user=await ensureAdmin();const res=await reviewPayment(paymentId,user.id,action,notes);if(res.success){revalidatePath('/admin/payments');revalidatePath('/admin')}return res}
export async function createAgentPayoutAction(formData:FormData){const user=await ensureAdmin();const agentId=String(formData.get('agent_id')||'').trim();const amount=Number(formData.get('amount'));const paymentMethod=String(formData.get('payment_method')||'manual').trim();const reference=String(formData.get('reference')||'').trim();const notes=String(formData.get('notes')||'').trim();if(!agentId||!Number.isFinite(amount)||amount<=0)return{error:'أدخل الوكيل والمبلغ بشكل صحيح'};const supabase=await createClient();const{data:agent,error:agentError}=await(supabase as any).from('agents').select('id,is_active').eq('id',agentId).single();if(agentError||!agent||!agent.is_active)return{error:'الوكيل غير موجود أو غير نشط'};const{error}=await(supabase as any).from('agent_payouts').insert({agent_id:agentId,amount,payment_method:paymentMethod,reference,notes,status:'pending',created_by:user.id});if(error)return{error:'فشل تسجيل مستحق الوكيل'};revalidatePath('/admin/agent-payouts');revalidatePath('/agent/payments');revalidatePath('/agent');return{success:true}}
export async function updateAgentPayoutStatusAction(payoutId:string,status:'confirmed'|'rejected',notes?:string){const user=await ensureAdmin();const supabase=await createClient();const{error}=await(supabase as any).from('agent_payouts').update({status,reviewed_by:user.id,reviewed_at:new Date().toISOString(),notes:notes||undefined,updated_at:new Date().toISOString()}).eq('id',payoutId);if(error)return{error:'فشل تحديث حالة مستحق الوكيل'};revalidatePath('/admin/agent-payouts');revalidatePath('/agent/payments');revalidatePath('/agent');return{success:true}}
