'use server';
import { revalidatePath } from 'next/cache';
import { getCurrentUser } from '@/lib/services/auth';
import { createClient, createAdminClient } from '@/lib/supabase/server';
import { reviewPayment } from '@/lib/services/payments';

async function ensureAdmin(){const user=await getCurrentUser();if(!user||user.role!=='admin')throw new Error('غير مصرح — صلاحيات إدارة مطلوبة');return user;}
export async function createAgentAccountAction(formData:FormData){await ensureAdmin();const email=String(formData.get('email')||'').trim().toLowerCase();const password=String(formData.get('password')||'');const fullName=String(formData.get('full_name')||'').trim();const phone=String(formData.get('phone')||'').trim();const regionId=String(formData.get('region_id')||'').trim();if(!email||!password||!fullName||!regionId)return{error:'يرجى إدخال الاسم والبريد وكلمة المرور والمنطقة'};if(password.length<6)return{error:'كلمة المرور يجب أن تكون 6 أحرف على الأقل'};const adminSupabase=await createAdminClient();const{data:existingUser}=await adminSupabase.from('users').select('id,role').eq('email',email).maybeSingle();if(existingUser)return{error:'هذا البريد الإلكتروني مستخدم بالفعل'};const{data:authData,error:authError}=await adminSupabase.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{full_name:fullName,phone,role:'agent'}});if(authError||!authData.user)return{error:authError?.message||'فشل إنشاء حساب الوكيل'};const userId=authData.user.id;const{error:userError}=await adminSupabase.from('users').insert({id:userId,email,full_name:fullName,phone,role:'agent',is_active:true,avatar_url:''} as never);if(userError){await adminSupabase.auth.admin.deleteUser(userId);return{error:'فشل إنشاء ملف الوكيل: '+userError.message}}const{error:agentError}=await adminSupabase.from('agents').insert({user_id:userId,region_id:regionId,is_active:true} as never);if(agentError){await adminSupabase.from('users').delete().eq('id',userId);await adminSupabase.auth.admin.deleteUser(userId);return{error:'فشل ربط الوكيل بالمنطقة: '+agentError.message}}const base=process.env.NEXT_PUBLIC_APP_URL||'https://engz-ochre.vercel.app';const msg=`مرحباً ${fullName}، تم إنشاء حسابك كوكيل في إنجز.\n\nرابط الوكيل:\n${base}/agent\n\nالبريد: ${email}\nكلمة المرور: ${password}\n\nيمكنك تغيير كلمة المرور من حسابك.`;const digits=phone.replace(/\D/g,'').replace(/^0/,'20');const whatsappUrl=digits?`https://wa.me/${digits}?text=${encodeURIComponent(msg)}`:undefined;revalidatePath('/admin/regions');revalidatePath('/admin');return{success:true,whatsappUrl}}
export async function updatePricingSettingsAction(formData:FormData){await ensureAdmin();const supabase=await createClient();const base=Number(formData.get('base_delivery_fee'));const baseDistance=Number(formData.get('base_distance_km'));const extra=Number(formData.get('additional_km_fee'));const commission=Number(formData.get('driver_commission_per_order')||6);const platform=Number(formData.get('platform_share_per_agent_order')||2.5);const agentShare=Number(formData.get('agent_share_per_order')||3.5);if(![base,baseDistance,extra,commission,platform,agentShare].every(Number.isFinite)||base<0||baseDistance<0||extra<0)return{error:'أدخل قيم التسعير بشكل صحيح'};if(Math.abs(platform+agentShare-commission)>0.001)return{error:'نصيب المنصة والوكيل يجب أن يساوي عمولة الطلب'};const{error}=await supabase.from('pricing_settings').update({base_delivery_fee:base,base_distance_km:baseDistance,additional_km_fee:extra,free_orders:3,driver_commission_per_order:commission,platform_share_per_agent_order:platform,agent_share_per_order:agentShare,updated_at:new Date().toISOString()} as never).eq('is_active',true);if(error)return{error:'فشل حفظ إعدادات التسعير'};revalidatePath('/admin/pricing');return{success:true}}export async function addDistanceTierAction(_formData?:FormData){return{error:'شرائح المسافات القديمة ملغاة. استخدم إعدادات التسعير الجديدة.'}}
export async function deleteDistanceTierAction(_id?:string){return{error:'شرائح المسافات القديمة ملغاة.'}}
export async function addCommissionTierAction(_formData?:FormData){return{error:'شرائح العمولة القديمة ملغاة. استخدم إعدادات التسعير الجديدة.'}}
export async function deleteCommissionTierAction(_id?:string){return{error:'شرائح العمولة القديمة ملغاة.'}}
export async function createRegionAction(formData:FormData){await ensureAdmin();const supabase=await createClient();const{error}=await supabase.from('regions').insert({name:String(formData.get('name')),name_ar:String(formData.get('name_ar')),whatsapp:String(formData.get('whatsapp')||''),instagram:String(formData.get('instagram')||''),is_active:true} as never);if(error)return{error:'فشل إنشاء المنطقة'};revalidatePath('/admin/regions');return{success:true}}
export async function toggleDriverBlockAction(driverId:string,isBlocked:boolean){await ensureAdmin();const supabase=await createClient();const{error}=await supabase.from('drivers').update({is_blocked:isBlocked} as never).eq('id',driverId);if(error)return{error:'فشل تغيير حالة الحظر'};revalidatePath('/admin/drivers');return{success:true}}
export async function adminReviewPaymentAction(paymentId:string,action:'confirmed'|'rejected',notes?:string){const user=await ensureAdmin();const res=await reviewPayment(paymentId,user.id,action,notes);if(res.success){revalidatePath('/admin/payments');revalidatePath('/admin')}return res}
export async function createAgentPayoutAction(formData:FormData){const user=await ensureAdmin();const agentId=String(formData.get('agent_id')||'').trim();const amount=Number(formData.get('amount'));const paymentMethod=String(formData.get('payment_method')||'manual').trim();const reference=String(formData.get('reference')||'').trim();const notes=String(formData.get('notes')||'').trim();if(!agentId||!Number.isFinite(amount)||amount<=0)return{error:'أدخل الوكيل والمبلغ بشكل صحيح'};const supabase=await createClient();const{data:agent,error:agentError}=await(supabase as any).from('agents').select('id,is_active').eq('id',agentId).single();if(agentError||!agent||!agent.is_active)return{error:'الوكيل غير موجود أو غير نشط'};const{error}=await(supabase as any).from('agent_payouts').insert({agent_id:agentId,amount,payment_method:paymentMethod,reference,notes,status:'pending',created_by:user.id});if(error)return{error:'فشل تسجيل مستحق الوكيل'};revalidatePath('/admin/agent-payouts');revalidatePath('/agent/payments');revalidatePath('/agent');return{success:true}}
export async function updateAgentPayoutStatusAction(payoutId:string,status:'confirmed'|'rejected',notes?:string){const user=await ensureAdmin();const supabase=await createClient();const{error}=await(supabase as any).from('agent_payouts').update({status,reviewed_by:user.id,reviewed_at:new Date().toISOString(),notes:notes||undefined,updated_at:new Date().toISOString()}).eq('id',payoutId);if(error)return{error:'فشل تحديث حالة مستحق الوكيل'};revalidatePath('/admin/agent-payouts');revalidatePath('/agent/payments');revalidatePath('/agent');return{success:true}}


export async function saveAdminPaymentMethodAction(formData:FormData){await ensureAdmin();const db=await createAdminClient();const methodKey=String(formData.get('method_key')||'').trim();const methodName=String(formData.get('method_name')||methodKey).trim();const accountName=String(formData.get('account_name')||'').trim();const accountNumber=String(formData.get('account_number')||'').trim();const instructions=String(formData.get('instructions')||'').trim();if(!methodKey||!accountNumber)return{error:'اختر طريقة التحويل وأدخل بيانات الحساب'};const{error}=await db.from('payment_methods').upsert({method_key:methodKey,method_name:methodName,account_name:accountName,account_number:accountNumber,instructions,is_active:true,updated_at:new Date().toISOString()},{onConflict:'method_key'});if(error)return{error:'فشل حفظ بيانات التحويل'};revalidatePath('/admin/payments');revalidatePath('/driver/wallet');return{success:true}}\n