alter table public.pricing_settings add column if not exists base_distance_km numeric not null default 4;
alter table public.pricing_settings add column if not exists additional_km_fee numeric not null default 3;
alter table public.drivers add column if not exists age integer;
alter table public.drivers add column if not exists address text not null default '';
alter table public.drivers add column if not exists vehicle_type text not null default '';
alter table public.drivers add column if not exists verification_complete boolean not null default true;
alter table public.drivers add column if not exists verification_id_card_front_url text not null default '';
alter table public.drivers add column if not exists verification_id_card_back_url text not null default '';
alter table public.drivers add column if not exists verification_personal_photo_url text not null default '';
create table if not exists public.admin_payment_methods(id uuid primary key default gen_random_uuid(),title text not null default 'بيانات السداد',method text not null,account_name text not null default '',account_number text not null default '',instructions text not null default '',is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.complaints(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id) on delete cascade,customer_id uuid not null references public.users(id) on delete cascade,driver_id uuid references public.drivers(id) on delete set null,agent_id uuid references public.agents(id) on delete set null,subject text not null default 'شكوى على الطيار',body text not null,status text not null default 'new' check(status in ('new','agent_review','agent_action','escalated','resolved')),agent_action text not null default '',escalated_at timestamptz,resolved_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists complaints_agent_idx on public.complaints(agent_id,created_at desc);
alter table public.admin_payment_methods enable row level security;
alter table public.complaints enable row level security;
drop policy if exists "admin payment methods read" on public.admin_payment_methods;
drop policy if exists "admin payment methods write" on public.admin_payment_methods;
create policy "admin payment methods read" on public.admin_payment_methods for select to authenticated using((select public.get_user_role())='admin');
create policy "admin payment methods write" on public.admin_payment_methods for all to authenticated using((select public.get_user_role())='admin') with check((select public.get_user_role())='admin');
drop policy if exists "complaints customer read" on public.complaints;
drop policy if exists "complaints customer insert" on public.complaints;
drop policy if exists "complaints agent update" on public.complaints;
create policy "complaints customer read" on public.complaints for select to authenticated using(customer_id=auth.uid() or (select public.get_user_role())='admin' or agent_id in(select id from public.agents where user_id=auth.uid()));
create policy "complaints customer insert" on public.complaints for insert to authenticated with check(customer_id=auth.uid());
create policy "complaints agent update" on public.complaints for update to authenticated using((select public.get_user_role())='admin' or agent_id in(select id from public.agents where user_id=auth.uid())) with check((select public.get_user_role())='admin' or agent_id in(select id from public.agents where user_id=auth.uid()));